image:
  file: .gitpod.Dockerfile


tasks:
  - init: |
      # Python environment setup
      sudo apt update
      sudo apt install -y python3.12-venv docker.io
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
      pip install dspy
      pip install openpipe-art

      # Pull SurrealDB Docker image
      docker pull surrealdb/surrealdb:latest
    command: |
      # Activate Python env
      source venv/bin/activate

      # Start SurrealDB in background
      docker run -d -p 8000:8000 --name surreal surrealdb/surrealdb start --log trace --user root --pass root

      # Run your app
      python main.py

ports:
  - port: 8000
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
