# automations.yml
automations:
  start-docker:
    trigger: onStart
    steps:
      - name: Add gitpod user to docker group
        run: sudo adduser gitpod docker || true

      - name: Start Docker daemon
        run: |
          if ! pgrep dockerd > /dev/null; then
            echo "Starting Docker daemon..."
            sudo dockerd > /tmp/dockerd.log 2>&1 &
            sleep 5
          fi

      - name: Verify Docker
        run: docker info || cat /tmp/dockerd.log
