# fly.toml app configuration file generated for mcp-platform on 2024-01-01
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mcp-platform'
primary_region = 'ord'
kill_signal = 'SIGTERM'
kill_timeout = '5s'

[build]
  dockerfile = "Dockerfile"

[env]
  PHX_HOST = "mcp-platform.fly.dev"
  PORT = "4000"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

[[statics]]
  guest_path = '/app/priv/static'
  url_prefix = '/static'

[mounts]
  source = "data"
